# fly.toml app configuration file generated for bits-and-bytes-web on 2024-03-13T12:42:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bits-and-bytes-web'
primary_region = 'ord'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
